// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3F9JmkjQQWbgf8AQJxMdY4efnFeuH74o',
    appId: '1:518346157887:web:29705647d11a7414bded8a',
    messagingSenderId: '518346157887',
    projectId: 'wordplaywonderlandver1',
    authDomain: 'wordplaywonderlandver1.firebaseapp.com',
    storageBucket: 'wordplaywonderlandver1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq98G37itI0wXtkg4CiVrqXPTQsnxYjtM',
    appId: '1:518346157887:android:ad10c661ec0b9f9bbded8a',
    messagingSenderId: '518346157887',
    projectId: 'wordplaywonderlandver1',
    storageBucket: 'wordplaywonderlandver1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQyc7ld8AKl8P1ZHgQTG-X8c-1mLHJ-S0',
    appId: '1:518346157887:ios:aedc3a3175c23070bded8a',
    messagingSenderId: '518346157887',
    projectId: 'wordplaywonderlandver1',
    storageBucket: 'wordplaywonderlandver1.appspot.com',
    iosClientId: '518346157887-g1mpvsjr702d1ehqkfg7i4np2v31ok4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordPlayWonderland',
  );
}
